INSERT INTO INVENTORY
VALUES (1, 'name01', 0);
INSERT INTO INVENTORY
VALUES (2, 'name02', 0);
INSERT INTO INVENTORY
VALUES (3, 'name03', 0);
INSERT INTO INVENTORY
VALUES (4, 'name04', 0);
INSERT INTO INVENTORY
VALUES (5, 'name05', 0);
INSERT INTO INVENTORY
VALUES (6, 'name06', 0);
INSERT INTO INVENTORY
VALUES (7, 'name07', 0);
INSERT INTO INVENTORY
VALUES (8, 'name08', 0);
INSERT INTO INVENTORY
VALUES (9, 'name09', 0);
INSERT INTO INVENTORY
VALUES (10, 'name10', 0);
